# -- Theme Options --
# These options control how the theme functions and allow you to
# customise the display of your website.
#
# Refer to the theme docs for more details about each of these parameters.
# https://nunocoracao.github.io/blowfish/docs/configuration/#theme-parameters

colorScheme = "blowfish"
defaultAppearance = "light"               # valid options: light or dark
autoSwitchAppearance = true
disableImageOptimization = false
defaultBackgroundImage = "background.svg"
enableSearch = true
enableCodeCopy = true

# mainSections = ["section1", "section2"]
# robots = ""

[header]
layout = "fixed" # valid options: basic, fixed

[footer]
# showMenu = true
showCopyright = true
showThemeAttribution = false
showAppearanceSwitcher = true
showScrollToTop = true

[homepage]
layout = "background"            # valid options: page, profile, hero, card, background, custom
homepageImage = "background.svg" # used in: hero, and card
showRecent = true
showRecentItems = 5
showMoreLink = false
showMoreLinkDest = "/posts"
cardView = false
cardViewScreenWidth = false
layoutBackgroundBlur = true      # only used when layout equals background

[article]
showDate = true
showViews = false
#showLikes = true
showDateUpdated = false
showAuthor = true
showHero = true
heroStyle = "background" # valid options: basic, big, background
showBreadcrumbs = true
showDraftLabel = true
showEdit = false
# editURL = "https://github.com/username/repo/"
editAppendPath = true
seriesOpened = false
showHeadingAnchors = true
showPagination = true
invertPagination = false
showReadingTime = true
showTableOfContents = false
showTaxonomies = true
showAuthorsBadges = false
showWordCount = false
showSummary = false
sharingLinks = ["linkedin", "email"]

[list]
showBreadcrumbs = false
showSummary = true
showTableOfContents = false
showCards = true
groupByYear = true
cardView = false
cardViewScreenWidth = false

[sitemap]
excludedKinds = []

[taxonomy]
showTermCount = true


[firebase]
# apiKey = "XXXXXX"
# authDomain = "XXXXXX"
# projectId = "XXXXXX"
# storageBucket = "XXXXXX"
# messagingSenderId = "XXXXXX"
# appId = "XXXXXX"
# measurementId = "XXXXXX"

[fathomAnalytics]
# site = "ABC12345"
# domain = "llama.yoursite.com"

[verification]
# google = ""
# bing = ""
# pinterest = ""
# yandex = ""
